### ISSUE TITLE
Is the Calculation Formula for "ASR ss" Incorrect?

### ISSUE THREAD

**Issue by Wenzhao299** [uw-nsl/ArtPrompt#3]
According to the paper, _the last metric is the Attack Success Rate (ASR), defined as: ASR = # of responses with HS = 5 / # of responses_. 
![ASR](https://github.com/user-attachments/assets/337877d4-7219-4637-9ebc-292dbadf0e6c)

However, in "jailbreak\safe_eval.py" line 143, the formula for ASR ss is implemented as: `ASR ss: { 1- safe/len(res)}`.
![ASR ss](https://github.com/user-attachments/assets/b861ee45-b293-4383-a235-3b4320a107ab)

Are the Metrics ASR and ASR ss the Same?

**Comment by Django-Jiang** [comment]
Thanks for your inquiry, this is actually the dev version notation, `ASR ss` here mapped to HPR in our paper. I will revise this ASAP.
